run:
  timeout: 5m

linters-settings:
  gocritic:
    disabled-checks:
      - exitAfterDefer
  gofumpt:
    lang-version: "1.23"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - cyclop
    - dogsled
    - durationcheck
    - exportloopref
    - exhaustive
    - errname
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - godox
    - nolintlint
    - misspell
    - forcetypeassert
    - gocognit
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - exportloopref
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - goprintffuncname
    - whitespace
    - thelper
