version: '3.8'

services:
  db:
    image: postgres:13.3
    dns_search: ''
    networks:
      - net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: edgetx
      POSTGRES_DB: cloudbuild
      POSTGRES_PASSWORD: psw

  db-test:
    image: postgres:13.3
    dns_search: ''
    networks:
      - net
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: edgetx
      POSTGRES_DB: cloudbuild
      POSTGRES_PASSWORD: psw

  ci:
    build:
      context: .
    privileged: true
    env_file:
      - ./test.env
    networks:
      - net
    depends_on:
      - db-test
      - db
    volumes:
      - ./:/home/rootless/src:cached
    command: [ "bash" ]

  api:
    dns_search: ''
    build:
      context: .
    privileged: true
    env_file:
      - ./api.env
    networks:
      - net
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/rootless/src:cached
    command: bash -c "make build-server && ./bin/server"

  worker:
    build:
      context: .
    privileged: true
    env_file:
      - ./api.env
    networks:
      - net
    depends_on:
      - db
    volumes:
      - ./:/home/rootless/src:cached
      - ./data:/home/rootless/.local/share/containers/storage
    command: bash -c "make build-worker && ./bin/worker"

networks:
  net:
