version: '3.8'

services:
  db:
    image: postgres:13.3
    dns_search: ''
    networks:
      - net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: edgetx
      POSTGRES_DB: cloudbuild
      POSTGRES_PASSWORD: psw

  api:
    image: cloudbuild
    command: ./ebuild run api
    build:
      context: .
      dockerfile: Dockerfile.production
    env_file:
      - ./api.env
    networks:
      - net
    depends_on:
      - db
    ports:
      - "3000:3000"

  worker:
    image: cloudbuild
    command: ./ebuild run worker
    privileged: true
    env_file:
      - ./api.env
    networks:
      - net
    depends_on:
      - db

networks:
  net:
