version: '3.8'

services:
  db:
    image: postgres:13.3
    dns_search: ''
    networks:
      - net
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: edgetx
      POSTGRES_DB: cloudbuild
      POSTGRES_PASSWORD: psw

  api:
    image: cloudbuild
    command: ./ebuild run api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./api.env
    networks:
      - net
    volumes:
      - firmwares:/home/rootless/src/static/firmwares
    depends_on:
      - db
    ports:
      - "3000:3000"

  worker:
    image: cloudbuild
    command: ./ebuild run worker
    privileged: true
    env_file:
      - ./api.env
    networks:
      - net
    volumes:
      - firmwares:/home/rootless/src/static/firmwares
    depends_on:
      - db
      - api

networks:
  net:

volumes:
  db-data:
  firmwares:
