name: Run tests

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        name: Test
        runs-on: ubuntu-22.04
        env:
            EBUILD_LOG_LEVEL: "debug"
            EBUILD_DATABASE_DSN: "host=localhost user=edgetx password=psw dbname=cloudbuild port=5432 sslmode=disable"

        services:
            postgres:
                image: postgres:13.3
                env:
                    POSTGRES_USER: edgetx
                    POSTGRES_DB: cloudbuild
                    POSTGRES_PASSWORD: psw
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            -   name: Set up Go
                uses: actions/setup-go@v3
                with:
                    go-version: ^1.20.0
                id: go

            -   name: Check out code into the Go module directory
                uses: actions/checkout@v3

            -   name: Lint
                run: make lint

            -   name: Test
                run: make test
